branches:
  only:
    - master
language: c
cache: apt
before_install:
  - sudo add-apt-repository ppa:jbboehr/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq ragel libev-dev liburcu-dev libunwind7-dev libmaxminddb-dev libsocket6-perl libio-socket-inet6-perl libwww-perl libhttp-daemon-perl lcov
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/l/lcov/lcov_1.10-1_all.deb
  - sudo dpkg -i lcov_1.10-1_all.deb
  - gem install coveralls-lcov
before_script:
  - autoreconf -vif
matrix:
  include:
    - compiler: clang
      env: GDNSD_TRAVIS_BUILD=optimized
    - compiler: gcc
      env: GDNSD_TRAVIS_BUILD=optimized
    - compiler: gcc
      env: GDNSD_TRAVIS_BUILD=coveralls
script:
  - ./qa/travis-build.sh
