language: c
compiler:
  - gcc
  - clang
script: autoreconf -vi && ./configure --disable-silent-rules && make && make test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ragel libev-dev liburcu-dev libsocket6-perl libio-socket-inet6-perl libwww-perl libhttp-daemon-perl geoip-database
